"""
Artemis provider - chain-level analytics and developer activity.
API docs: https://docs.artemisanalytics.com
"""

import time
from typing import Any, Dict, List, Optional

from .base import BaseProvider, MetricResult


class ArtemisProvider(BaseProvider):

    @property
    def name(self) -> str:
        return "artemis"

    @property
    def base_url(self) -> str:
        return "https://api.artemisanalytics.com/v1"

    def _build_headers(self) -> Dict[str, str]:
        return {
            "Accept": "application/json",
            "x-api-key": self.api_key,
        }

    def _parse_timeseries(self, data: Any, metric_name: str) -> List[MetricResult]:
        results = []
        entries = data.get("data", []) if isinstance(data, dict) else data if isinstance(data, list) else []
        for entry in entries:
            ts = entry.get("timestamp", entry.get("date", int(time.time())))
            if isinstance(ts, str):
                from datetime import datetime, timezone
                try:
                    ts = int(datetime.fromisoformat(ts.replace("Z", "+00:00")).timestamp())
                except ValueError:
                    ts = int(time.time())
            results.append(MetricResult(
                metric_name=metric_name,
                value=entry.get("value", entry),
                timestamp=ts,
                source=self.name,
                metadata=entry if isinstance(entry, dict) else {},
            ))
        return results

    async def get_daily_active_addresses(self, chain: str = "ethereum") -> List[MetricResult]:
        """Daily active addresses for a chain."""
        data = await self._get(
            "chains/metrics",
            params={"chain": chain, "metric": "daa", "interval": "daily"},
        )
        return self._parse_timeseries(data, "daily_active_addresses")

    async def get_daily_transactions(self, chain: str = "ethereum") -> List[MetricResult]:
        """Daily transaction count for a chain."""
        data = await self._get(
            "chains/metrics",
            params={"chain": chain, "metric": "daily_txns", "interval": "daily"},
        )
        return self._parse_timeseries(data, "daily_transactions")

    async def get_developer_activity(self, ecosystem: str = "ethereum") -> List[MetricResult]:
        """Developer activity - commits and active repos."""
        data = await self._get(
            "developer/activity",
            params={"ecosystem": ecosystem},
        )
        return self._parse_timeseries(data, "developer_activity")

    async def get_ecosystem_comparison(self, chains: Optional[List[str]] = None) -> List[MetricResult]:
        """Compare metrics across multiple chains."""
        chain_list = chains or ["ethereum", "bsc", "solana", "arbitrum", "polygon"]
        import asyncio
        tasks = []
        for chain in chain_list:
            tasks.append(self.get_daily_active_addresses(chain))
        results = await asyncio.gather(*tasks, return_exceptions=True)
        combined = []
        for i, r in enumerate(results):
            if isinstance(r, list) and r:
                latest = r[-1]
                latest.metric_name = f"daa_{chain_list[i]}"
                combined.append(latest)
        return combined

    async def get_fee_revenue(self, chain: str = "ethereum") -> List[MetricResult]:
        """Fee revenue generated by the chain."""
        data = await self._get(
            "chains/metrics",
            params={"chain": chain, "metric": "fees", "interval": "daily"},
        )
        return self._parse_timeseries(data, "fee_revenue")

    async def get_all_metrics(self, chain: str = "ethereum") -> List[MetricResult]:
        """Fetch all available metrics for a chain."""
        import asyncio
        tasks = [
            self.get_daily_active_addresses(chain),
            self.get_daily_transactions(chain),
            self.get_fee_revenue(chain),
        ]
        results = await asyncio.gather(*tasks, return_exceptions=True)
        combined = []
        for r in results:
            if isinstance(r, list) and r:
                combined.append(r[-1])
        return combined
